/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SEC_CORE_DEFS_H
#define SEC_CORE_DEFS_H

#include "shikra_def.h"

#define APSS_BANKED_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00000000)
#define APSS_BANKED_APC_SECURE_ADDR		(APSS_BANKED_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_BANKED_APC_SECURE_RMSK		0x1

#define APSS_WDT_TMR1_APSS_WDT_REG_BASE	(QTI_APSS_HM_BASE + 0x00410000)
#define APSS_WDT_TMR1_WDOG_SECURE_ADDR		(APSS_WDT_TMR1_APSS_WDT_REG_BASE + 0x0)
#define APSS_WDT_TMR1_WDOG_SECURE_RMSK		0x1

#define APSS_SHARED_APSS_SHARED_REG_BASE	(QTI_APSS_HM_BASE + 0x00600000)
#define APSS_SHARED_KRYO_RVBARADDR_LO_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0xf010)
#define APSS_SHARED_KRYO_RVBARADDR_HI_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0xf014)
#define APSS_SHARED_SHR_SECURE_ADDR		(APSS_SHARED_APSS_SHARED_REG_BASE + 0x4)
#define APSS_SHARED_SHR_SECURE_RMSK		0x0

#define APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00800000)
#define APSS_ALIAS_0_APC_SECURE_ADDR		(APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_ALIAS_0_APC_SECURE_RMSK		0x1
#define APSS_ALIASn_APC_SECURE_OFFSET_TO_NEXT	0x10000
#define APSS_ALIASn_APC_SECURE_MAX_INDEX	0x3

#define APSS_APSS_CL_IPM_REG_BASE		(QTI_APSS_HM_BASE + 0x00880000)
#define APSS_CL_SECURE_ADDR			(APSS_APSS_CL_IPM_REG_BASE + 0x0)
#define APSS_CL_SECURE_RMSK			0x1


#endif /* SEC_CORE_DEFS_H */