/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * ICB configuration hardware register address definitions for
 * Lemans (QCS9075).
 */

#ifndef QTI_ICBCFG_HWIO_H
#define QTI_ICBCFG_HWIO_H

#include <stdint.h>
#include <lib/mmio.h>

/*
 * TFA-compatible replacements for TZ HWIO macros used by icbcfg_query.c.
 *
 * HWIO_INXF(base, reg, field):
 *   Read the named field from register <reg> at absolute address <base>.
 *   <base> is the absolute address of the register (trans_bases[] already
 *   points directly at the register, so the offset is 0).
 *
 * HWIO_INXI(base, reg, index):
 *   Read indexed register <reg>[index] at absolute address <base>.
 *   The stride between consecutive entries is reg##_STRIDE bytes.
 */
#define HWIO_INXF(base, reg, field) \
	((mmio_read_32((uintptr_t)(base) + reg##_OFFSET) \
	  & reg##_##field##_BMSK) >> reg##_##field##_SHFT)

#define HWIO_INXI(base, reg, index) \
	mmio_read_32((uintptr_t)(base) + reg##_OFFSET + \
		     (uint32_t)(index) * reg##_STRIDE)

/*
 * LLCC BEAC address-translator register layout.
 *
 * trans_bases[0] is set to the absolute address of the
 * LLCC_BEAC_ADDR_TRANSLATOR_CFG register for the selected LLCC slice
 * (e.g. LLCC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG).  All offsets below are
 * relative to that same base.
 *
 * Register map (relative to LLCC_BEAC_ADDR_TRANSLATOR_CFG):
 *   +0x0000  ADDR_TRANSLATOR_CFG   (ERROR field at bit 0)
 *   +0x0010  ADDR_REGIONn_CFG0[n]  stride 0x20  (offset_lo[31:0])
 *   +0x0014  ADDR_REGIONn_CFG1[n]  stride 0x20  (offset_hi[31:0])
 *   +0x0018  ADDR_REGIONn_CFG2[n]  stride 0x20  (base_lo[31:0])
 *   +0x001C  ADDR_REGIONn_CFG3[n]  stride 0x20  (base_hi[31:0])
 */
#define LLCC_BEAC_ADDR_TRANSLATOR_CFG_OFFSET	0x0000U
#define LLCC_BEAC_ADDR_TRANSLATOR_CFG_ERROR_BMSK	0xFFFFFFFFU
#define LLCC_BEAC_ADDR_TRANSLATOR_CFG_ERROR_SHFT	0U

#define LLCC_BEAC_ADDR_REGIONn_CFG0_OFFSET	0x0010U
#define LLCC_BEAC_ADDR_REGIONn_CFG0_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_REGIONn_CFG1_OFFSET	0x0014U
#define LLCC_BEAC_ADDR_REGIONn_CFG1_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_REGIONn_CFG2_OFFSET	0x0018U
#define LLCC_BEAC_ADDR_REGIONn_CFG2_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_REGIONn_CFG3_OFFSET	0x001CU
#define LLCC_BEAC_ADDR_REGIONn_CFG3_STRIDE	0x0020U

/*
 * Additional region registers for segments >= ADDL_REGION_START (6+).
 * Used by ICBCFG_ADDR_TRANS_LLCC when num_segments > ADDL_REGION_START.
 * addl_trans_bases[] points to the base of the additional translator block.
 */
#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG0_OFFSET	0x0010U
#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG0_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG1_OFFSET	0x0014U
#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG1_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG2_OFFSET	0x0018U
#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG2_STRIDE	0x0020U

#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG3_OFFSET	0x001CU
#define LLCC_BEAC_ADDR_ADDL_REGIONn_CFG3_STRIDE	0x0020U

/* MA (multi-address) region variants — same layout, different base offset */
#define LLCC_BEAC_MA_ADDR_REGIONn_CFG0_OFFSET	0x0110U
#define LLCC_BEAC_MA_ADDR_REGIONn_CFG0_STRIDE	0x0020U

#define LLCC_BEAC_MA_ADDR_REGIONn_CFG1_OFFSET	0x0114U
#define LLCC_BEAC_MA_ADDR_REGIONn_CFG1_STRIDE	0x0020U

#define LLCC_BEAC_MA_ADDR_REGIONn_CFG2_OFFSET	0x0118U
#define LLCC_BEAC_MA_ADDR_REGIONn_CFG2_STRIDE	0x0020U

#define LLCC_BEAC_MA_ADDR_REGIONn_CFG3_OFFSET	0x011CU
#define LLCC_BEAC_MA_ADDR_REGIONn_CFG3_STRIDE	0x0020U

/*
 * MemNOC address translator register layout.
 * Used for ICBCFG_ADDR_TRANS_NOC targets.
 *
 * Register map (relative to MEMNOC_ADDR_TRANSLATOR_CFG base):
 *   +0x0000  ADDR_TRANSLATOR_CFG   (ERROR field at bit 0)
 *   +0x0010  ADDR_TRANSLATOR_BASEn_LOW[n]   stride 0x10
 *   +0x0014  ADDR_TRANSLATOR_BASEn_HIGH[n]  stride 0x10
 *   +0x0018  ADDR_TRANSLATOR_OFFSETn_LOW[n] stride 0x10
 *   +0x001C  ADDR_TRANSLATOR_OFFSETn_HIGH[n] stride 0x10
 */
#define MEMNOC_ADDR_TRANSLATOR_CFG_OFFSET	0x0000U
#define MEMNOC_ADDR_TRANSLATOR_CFG_ERROR_BMSK	0xFFFFFFFFU
#define MEMNOC_ADDR_TRANSLATOR_CFG_ERROR_SHFT	0U

#define MEMNOC_ADDR_TRANSLATOR_BASEn_LOW_OFFSET	0x0010U
#define MEMNOC_ADDR_TRANSLATOR_BASEn_LOW_STRIDE	0x0010U

#define MEMNOC_ADDR_TRANSLATOR_BASEn_HIGH_OFFSET	0x0014U
#define MEMNOC_ADDR_TRANSLATOR_BASEn_HIGH_STRIDE	0x0010U

#define MEMNOC_ADDR_TRANSLATOR_OFFSETn_LOW_OFFSET	0x0018U
#define MEMNOC_ADDR_TRANSLATOR_OFFSETn_LOW_STRIDE	0x0010U

#define MEMNOC_ADDR_TRANSLATOR_OFFSETn_HIGH_OFFSET	0x001CU
#define MEMNOC_ADDR_TRANSLATOR_OFFSETn_HIGH_STRIDE	0x0010U

/*
 * MC ISU address translator register layout.
 * Used for ICBCFG_ADDR_TRANS_MC targets.
 *
 * Two register sets:
 *   REGIONn (segments 0..5):
 *     +0x0010  MC_ISU_ADDR_REGIONn_CFG0[n]  stride 0x20  (offset_lo)
 *     +0x0014  MC_ISU_ADDR_REGIONn_CFG1[n]  stride 0x20  (offset_hi)
 *     +0x0018  MC_ISU_ADDR_REGIONn_CFG2[n]  stride 0x20  (base_lo)
 *     +0x001C  MC_ISU_ADDR_REGIONn_CFG3[n]  stride 0x20  (base_hi)
 *   REGION_n (segments 6+, offset-only):
 *     +0x0110  MC_ISU_ADDR_REGION_n_CFG0[n] stride 0x10  (offset_lo)
 *     +0x0114  MC_ISU_ADDR_REGION_n_CFG1[n] stride 0x10  (offset_hi)
 */
#define MC_ISU_ADDR_TRANSLATOR_CFG_OFFSET	0x0000U
#define MC_ISU_ADDR_TRANSLATOR_CFG_ERROR_BMSK	0xFFFFFFFFU
#define MC_ISU_ADDR_TRANSLATOR_CFG_ERROR_SHFT	0U

#define MC_ISU_ADDR_REGIONn_CFG0_OFFSET	0x0010U
#define MC_ISU_ADDR_REGIONn_CFG0_STRIDE	0x0020U

#define MC_ISU_ADDR_REGIONn_CFG1_OFFSET	0x0014U
#define MC_ISU_ADDR_REGIONn_CFG1_STRIDE	0x0020U

#define MC_ISU_ADDR_REGIONn_CFG2_OFFSET	0x0018U
#define MC_ISU_ADDR_REGIONn_CFG2_STRIDE	0x0020U

#define MC_ISU_ADDR_REGIONn_CFG3_OFFSET	0x001CU
#define MC_ISU_ADDR_REGIONn_CFG3_STRIDE	0x0020U

#define MC_ISU_ADDR_REGION_n_CFG0_OFFSET	0x0110U
#define MC_ISU_ADDR_REGION_n_CFG0_STRIDE	0x0010U

#define MC_ISU_ADDR_REGION_n_CFG1_OFFSET	0x0114U
#define MC_ISU_ADDR_REGION_n_CFG1_STRIDE	0x0010U


/* Base addresses */
#define DDR_SS_BASE			0x24000000U
#define CORE_TOP_CSR_BASE		0x01f00000U
#define LPASS_BASE			0x06000000U
#define SYSTEM_NOC_WRAPPER_BASE		0x01680000U
#define MMSS_NOC_WRAPPER_BASE		0x01780000U

/*
 * Maximum physical DDR address for Lemans (36-bit address space).
 * Used as the upper bound of the mappable DDR region.
 */
#define SCL_DDR_MAX_ALLOWABLE_ADDR	0xfffffffffULL

/*
 * LLCC BEAC address-translator configuration registers.
 * LLCC[n]_LLCC_BEAC0_REG_BASE = DDR_SS_BASE + 0x00260000 + n * 0x100000
 * LLCC_BEAC_ADDR_TRANSLATOR_CFG offset within BEAC block = 0x8000
 */
#define LLCC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00268000U)
#define LLCC1_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00368000U)
#define LLCC2_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00468000U)
#define LLCC3_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00568000U)
#define LLCC4_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00668000U)
#define LLCC5_LLCC_BEAC_ADDR_TRANSLATOR_CFG	(DDR_SS_BASE + 0x00768000U)

/*
 * TCSR: DDR channel-select mode fuse/register.
 * TCSR_TCSR_REGS_REG_BASE = CORE_TOP_CSR_BASE + 0x000c0000
 */
#define TCSR_REGS_BASE			(CORE_TOP_CSR_BASE + 0x000c0000U)
#define TCSR_TIMEOUT_INTR_CH2_CH4_OR_CH6_STATUS	(TCSR_REGS_BASE + 0x8088U)
#define TCSR_DDR_CH_SEL_MODE_BMSK	0x3U

/*
 * GEM_NOC dynamic-attribute registers.
 * GEM_NOC_REG_BASE = DDR_SS_BASE + 0x00100000
 */
#define GEM_NOC_BASE			(DDR_SS_BASE + 0x00100000U)

/* LOGUSEROV_LOW registers (log-user override enable) */
#define GEM_NOC_QNM_MNOC_HF0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe5028U)
#define GEM_NOC_QNM_MNOC_HF1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe6028U)
#define GEM_NOC_QNM_MNOC_SF0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe7028U)
#define GEM_NOC_QNM_MNOC_SF1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe8028U)
#define GEM_NOC_QNM_NSP_NOC0_0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe9028U)
#define GEM_NOC_QNM_NSP_NOC0_1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xea028U)
#define GEM_NOC_QNM_NSP_NOC1_0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xeb028U)
#define GEM_NOC_QNM_NSP_NOC1_1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xec028U)

/* LOGUSERVAL_LOW registers (log-user override value) */
#define GEM_NOC_QNM_MNOC_HF0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe5030U)
#define GEM_NOC_QNM_MNOC_HF1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe6030U)
#define GEM_NOC_QNM_MNOC_SF0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe7030U)
#define GEM_NOC_QNM_MNOC_SF1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe8030U)
#define GEM_NOC_QNM_NSP_NOC0_0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe9030U)
#define GEM_NOC_QNM_NSP_NOC0_1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xea030U)
#define GEM_NOC_QNM_NSP_NOC1_0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xeb030U)
#define GEM_NOC_QNM_NSP_NOC1_1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xec030U)

/* GEM_NOC ALM TCU cache-index and main-control registers */
#define GEM_NOC_ALM_GPU_TCU_DYNATTR_CACHEINDEXVAL_LOW	(GEM_NOC_BASE + 0xad050U)
#define GEM_NOC_ALM_GPU_TCU_DYNATTR_MAINCTL_LOW		(GEM_NOC_BASE + 0xad008U)
#define GEM_NOC_ALM_PCIE_TCU_DYNATTR_CACHEINDEXVAL_LOW	\
	(GEM_NOC_BASE + 0xae050U)
#define GEM_NOC_ALM_PCIE_TCU_DYNATTR_MAINCTL_LOW	(GEM_NOC_BASE + 0xae008U)
#define GEM_NOC_ALM_SYS_TCU_DYNATTR_CACHEINDEXVAL_LOW	(GEM_NOC_BASE + 0xaf050U)
#define GEM_NOC_ALM_SYS_TCU_DYNATTR_MAINCTL_LOW	(GEM_NOC_BASE + 0xaf008U)

/*
 * MMSS_NOC (MNOC) dynamic-attribute registers.
 * MNOC_SERVICE_NETWORK_REG_BASE = MMSS_NOC_WRAPPER_BASE + 0x00000000 (HF)
 * MNOC_SERVICENETWORK_REG_BASE  = MMSS_NOC_WRAPPER_BASE + 0x00020000 (SF)
 */
#define MNOC_HF_BASE			(MMSS_NOC_WRAPPER_BASE + 0x00000000U)
#define MNOC_SF_BASE			(MMSS_NOC_WRAPPER_BASE + 0x00020000U)

/* MNOC HF LOGUSEROV_LOW */
#define MMSS_NOC_QNM_CAMNOC_HF0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7028U)
#define MMSS_NOC_QNM_MDP0_0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x70a8U)
#define MMSS_NOC_QNM_MDP1_0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7128U)
#define MMSS_NOC_QNM_MDP0_1_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x71a8U)
#define MMSS_NOC_QNM_MDP1_1_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7228U)

/* MNOC HF LOGUSERVAL_LOW */
#define MMSS_NOC_QNM_CAMNOC_HF0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7030U)
#define MMSS_NOC_QNM_MDP0_0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x70b0U)
#define MMSS_NOC_QNM_MDP1_0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7130U)
#define MMSS_NOC_QNM_MDP0_1_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x71b0U)
#define MMSS_NOC_QNM_MDP1_1_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7230U)

/* MNOC SF LOGUSEROV_LOW */
#define MMSS_NOC_QNM_CAMNOC_ICP_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7028U)
#define MMSS_NOC_QNM_CAMNOC_SF0_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x70a8U)
#define MMSS_NOC_QNM_VIDEO0_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7128U)
#define MMSS_NOC_QNM_VIDEO1_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7188U)
#define MMSS_NOC_QNM_VIDEO_CVP_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7228U)
#define MMSS_NOC_QNM_VIDEO_V_CPU_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x72a8U)

/* MNOC SF LOGUSERVAL_LOW */
#define MMSS_NOC_QNM_CAMNOC_ICP_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7030U)
#define MMSS_NOC_QNM_CAMNOC_SF0_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x70b0U)
#define MMSS_NOC_QNM_VIDEO0_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7130U)
#define MMSS_NOC_QNM_VIDEO1_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7190U)
#define MMSS_NOC_QNM_VIDEO_CVP_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7230U)
#define MMSS_NOC_QNM_VIDEO_V_CPU_DYNATTR_LOGUSERVAL_LOW	\
	(MNOC_SF_BASE + 0x72b0U)

/*
 * SYSTEM_NOC dynamic-attribute registers.
 * SNOC_SERVICE_NETWORK_REG_BASE = SYSTEM_NOC_WRAPPER_BASE + 0x00000000
 */
#define SNOC_BASE			(SYSTEM_NOC_WRAPPER_BASE + 0x00000000U)

/* SNOC LOGUSEROV_LOW */
#define SYSTEM_NOC_QHM_GIC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xa028U)
#define SYSTEM_NOC_QNM_LPASS_NOC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xd028U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xf028U)

/* SNOC LOGUSERVAL_LOW */
#define SYSTEM_NOC_QHM_GIC_DYNATTR_LOGUSERVAL_LOW	(SNOC_BASE + 0xa030U)
#define SYSTEM_NOC_QNM_LPASS_NOC_DYNATTR_LOGUSERVAL_LOW (SNOC_BASE + 0xd030U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_LOGUSERVAL_LOW	(SNOC_BASE + 0xf030U)

/* SNOC XM_GIC transaction-type LUT and main-control */
#define SYSTEM_NOC_XM_GIC_DYNATTR_TRTYPELUT_LOW	(SNOC_BASE + 0xf038U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_MAINCTL_LOW		(SNOC_BASE + 0xf008U)

/*
 * LPASS_AG_NOC dynamic-attribute registers.
 * LPASS_AG_NOC_REG_BASE = LPASS_BASE + 0x01040000
 */
#define LPASS_AG_NOC_BASE		(LPASS_BASE + 0x01040000U)

#define LPASS_AG_NOC_QNM_LPASS_HW_AF_DYNATTR_MAINCTL_LOW \
					(LPASS_AG_NOC_BASE + 0x7008U)
#define LPASS_AG_NOC_QNM_LPASS_HW_AF_DYNATTR_TRTYPELUT_LOW \
					(LPASS_AG_NOC_BASE + 0x7038U)
#define LPASS_AG_NOC_QXM_LPASS_DSP_DYNATTR_MAINCTL_LOW \
					(LPASS_AG_NOC_BASE + 0x9008U)

#endif /* QTI_ICBCFG_HWIO_H */
