/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VMIDMT_TARGET_HWIO_H
#define VMIDMT_TARGET_HWIO_H

#include <shikra_def.h>

#define TCSR_TCSR_REGS_REG_BASE (QTI_CORE_TOP_CSR_BASE + 0x000c0000)
#define TCSR_TCSR_REGS_REG_BASE_SIZE 0x40000
#define TCSR_TCSR_REGS_REG_BASE_USED 0x3f01c

/*
 * VMIDMT error interrupt aggregation registers. Shikra reports all 18 VMIDMT
 * instances in a single register per interrupt, hence the 0x3ffff masks and
 * ACC_VMIDMT_ERR_INT_STATUS_REG_NUM == 1.
 */
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x2010)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ENABLE_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x2050)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ENABLE_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x3000)
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ENABLE_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x3040)
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ENABLE_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x4010)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ENABLE_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x4050)
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ENABLE_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x5000)
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_RMSK 0x3ffff

#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ENABLE_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x5040)
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ENABLE_RMSK 0x3ffff

#endif /* VMIDMT_TARGET_HWIO_H */
